### PR TITLE
Clarify some wording in external oasis repo instructions

### PR DESCRIPTION
**Pull request by DrDaveD**
From feedback from @kagross.

Please don't merge until Kyle has reviewed & approved.

### CODE REVIEW

**Comment by DrDaveD** [comment]
The travis failures do not appear to be related to this PR.

@kagross this is waiting on you.

**Comment by kagross** [comment]
Commented.  All seems to be good.

 

Kyle Gross

Open Science Grid Operations

Operations Support Manager

OSG Outreach Coordinator

Indiana University Research Technologies

**Comment by DrDaveD** [comment]
Ok good.  Do you have merge privileges or is someone else supposed to do that?

**Comment by kagross** [comment]
Ah, It didn’t look like I had merge privileges, but it seems I do.  I, too, was confused by that.  But I’ve merged it now.

 

Kyle Gross

Open Science Grid Operations

Operations Support Manager

OSG Outreach Coordinator

Indiana University Research Technologies

**Pull request merged**
